### ISSUE TITLE
plan for multiple fill for a slot

### ISSUE THREAD

**Issue by veeramarni** [BlackBoxVision/react-slot-and-fill#11]
Is this feature completed? I noticed it wasn' in the readme.

**Comment by JonatanSalas** [comment]
Hi @veeramarni! It's currently not completed, I will try to have implemented this weekend!

**Comment by mg901** [comment]
@JonatanSalas, hi! Thank  you for awesome tool, we are now in dire need of this functionality. Do you have plans to finish it or maybe I can help you?
